scheduler:
  daily_pull_time: "18:00"  # 6 PM IST (after market close)
  retry_attempts: 3
  retry_delay: 300  # 5 minutes
  rate_limit_delay: 1  # 1 second between symbols
  
data_sources:
  primary: "kiteconnect"
  fallback: "yfinance"
  
universe:
  nifty50: true
  nifty_next50: true
  custom_symbols: []
  
storage:
  bigquery:
    project_id: "ai-trading-gcp-459813"
    dataset: "trading_data"
    table: "daily_prices"
    
logging:
  level: "INFO"
  max_log_files: 30  # Keep logs for 30 days
  
notifications:
  email:
    enabled: false
    smtp_server: ""
    recipients: []
  slack:
    enabled: false
    webhook_url: ""
    
data_quality:
  enable_checks: true
  min_records_per_symbol: 1
  max_missing_days: 3
  alert_on_failures: true
